name: 'GitHub Actions IP-POOL'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '03 16 * * *'

jobs:
 Spider:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    # - name: 'Install dependencies'
    #   run: python -m pip install --upgrade pip
    - name: 'Install requirements'
      run: pip install -r ./Spider/requirements.txt
    - name: 'Working'
      run: bash ./Spider/main.sh




